### ISSUE TITLE
Transistions sometimes stutter

### ISSUE THREAD

**Issue by nyrrrr** [KoBeWi/Metroidvania-System#22] opened 2023-12-09 10:13 UTC
Some transitions are smooth between rooms, but some are "stuttering". 
In this example, the first one will always "stutter", the second one will always be smooth.

https://github.com/KoBeWi/Metroidvania-System/assets/2575407/27ae16ba-a54a-4806-8dbf-9e895421b88c

Have not figured out why that happens, yet

**Comment by nyrrrr** [comment] 2023-12-09 10:45
It appears as this issue only appears when going from left to right.

**Comment by KoBeWi** [comment] 2023-12-09 17:13
It looks like your character gets pushed to the previous room, so you switch rooms multiple times in a quick succession. This might be related to your previous issue and could be worked around by pushing the character forward after the transition.

**Comment by KoBeWi** [comment] 2024-02-20 22:47
Were you able to resolve this issue? Did you upgrade to 1.2 to use the new neighbor preview feature? You should be able to see whether your rooms are properly aligned.

**Comment by KoBeWi** [comment] 2024-05-17 12:36
No answer so I'll assume this is resolved in some way. If you still have this problem, I'll need some reproduction project to look into it.

**Closed by KoBeWi** 2024-05-17 12:36 UTC
