### ISSUE TITLE
Error when starting template game

### ISSUE THREAD

**Issue by JouBqa** [KoBeWi/Metroidvania-System#39] opened 2024-02-20 19:26 UTC
I get this error: 
Attempt to call function 'instantiate' in base 'null instance' on a null instance.

E 0:00:00:0841   MetSysGame.gd:40 @ load_room(): Resource file not found: res://SampleProject/Maps (expected type: )
  <C++ Error>    Condition "!file_check->file_exists(p_path)" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:279 @ _load()
  <Stack Trace>  MetSysGame.gd:40 @ load_room()
                 Game.gd:52 @ _ready()

The map files are in my projects folder in \Metroidvania-System-master\SampleProject\Maps
![image](https://github.com/KoBeWi/Metroidvania-System/assets/78951590/46c9e34c-40c8-4c77-b3f5-f79aaac3b3ed)

**Comment by KoBeWi** [comment] 2024-02-20 19:29
Same as #38

I fixed the cause, but save files from the broken version need to be manually deleted.

**Comment by JouBqa** [comment] 2024-02-20 19:37
I deleted the project and downloaded the zip and got the same error. I think I already had the zip. Is there somewhere else I need to delete save files than the project folder?

**Comment by KoBeWi** [comment] 2024-02-20 19:38
Saves are located in user directory, you can access it here:
![image](https://github.com/KoBeWi/Metroidvania-System/assets/2223172/9603d993-7467-4b40-a891-7d1dcffa434e)

**Comment by KoBeWi** [comment] 2024-02-27 13:20
Fixed by ac0f2b40620a2c15b5e3ec60520456fdc1e7999f

**Closed by KoBeWi** 2024-02-27 13:20 UTC
