### ISSUE TITLE
Error in sample project.

### ISSUE THREAD

**Issue by jalcazo** [KoBeWi/Metroidvania-System#38] opened 2024-02-14 01:02 UTC
"Attempt to call function 'instantiate' in base 'null instance' on a null instance." in this line:

	map = load(path).instantiate()

On the sample project. I can't run it. I'm sorry, it looks promising. Noob to Godot. What I'm doing wrong?

Thanks for your work.

**Comment by KoBeWi** [comment] 2024-02-14 01:06
Did you download the sample project from GitHub? The README specifically says to use the ZIP version instead of AssetLib one: https://github.com/KoBeWi/Metroidvania-System?tab=readme-ov-file#starting-sample-project

**Comment by jalcazo** [comment] 2024-02-14 01:13
Thank you for your superfast response. I cloned the repo with git. To make sure I downloaded again as ZIP as you suggested, I imported the project.godot and now it complains about failing scripts and then says "Could not resolve super class inheritance from "res://addons/MetroidVaniaSystem/Template/... etc."  in (0,0). Maybe the name of the folder should match "MetroidVaniaSystem" exactly? I'll try. I tried to reset godot after importing as you suggest with no luck. What is Assetlib? sorry for the noobness and thank your for your time.

**Comment by KoBeWi** [comment] 2024-02-14 01:19
What Godot version are you using?

**Comment by jalcazo** [comment] 2024-02-14 01:20
4.2.1 Windows, downloaded it some minutes ago.

**Comment by KoBeWi** [comment] 2024-02-14 01:38
I can't reproduce it.

What is the value of `path`?

**Comment by tewly27** [comment] 2024-02-14 21:28
In sample project I walk all the way left and it crash

**Comment by KoBeWi** [comment] 2024-02-14 22:07
@tewly27 That looks unrelated to the original issue, but I can confirm that it happens. It's caused by the use of UID in room's assigned scene.

**Comment by Unnamed1334** [comment] 2024-02-14 23:08
I think I ran into the same issue.

Steps to reproduce:
Open the sample project from Github.
Run the Game
Re-enter the save point to generate the save file.
Close the game.
Open the game.
The game fails to start giving:
"Attempt to call function 'instantiate' in base 'null instance' on a null instance." 
`path` value is `res://SampleProject/Maps/`

From what I could find, it looked to be because room_name of RoomInstance.gd wasn't being set. The empty name is being saved and causing the issue when trying to reload the room.
The save file has:
"current_room": "",

**Comment by KoBeWi** [comment] 2024-02-15 14:06
Fixed by 113c94a

**Closed by KoBeWi** 2024-02-15 14:06 UTC
