### ISSUE TITLE
Extra Room Node on reload

### ISSUE THREAD

**Issue by HeiMao808** [KoBeWi/Metroidvania-System#58] opened 2024-07-01 07:53 UTC
So this is a very odd bug(?) that I am running into. When my player dies anywhere on my map (so far) the game will respawn it normally WITH THE EXCEPTION of this one combination of circumstances.

![map layout](https://github.com/KoBeWi/Metroidvania-System/assets/13976820/100bae50-5b04-4be5-bf91-5c171e4dd6e5)

In the image above I have "S" marked as where the player's last save point is. When the player dies in the circled room they are not placed directly at the save point, but rather 2 room blocks up. On top of this, I get an additional node instance of the same room that ends up persisting when I change rooms.

![remote runtime](https://github.com/KoBeWi/Metroidvania-System/assets/13976820/88a04fd7-63cc-4a6c-8e30-687c3715012c)

I haven't got a clue why this is happening, but is there a way I can stop this extra child node? 

Here is my kill function in my player as a reference. I don't believe I have changed any code that involves loading rooms.

	func kill():
		if currentHealth <= 0:
			print("You Died")
			currentHealth = MaxHealth
			is_dead = false
			Game.get_singleton().reload_game()
			
		else:
			print("You Fell")
			currentHealth -= 1
			position = SafePosition.global_position

**Comment by KoBeWi** [comment] 2024-07-01 10:55
Looks like your player respawns outside the room, so the room loads and immediately transitions. As for double node, I'm not sure what causes it, but I observed it a few times with lava room in the example project. I was not able to reproduce it reliably.

**Comment by HeiMao808** [comment] 2024-07-01 18:45
I did recall the lava room being duplicated when I was trying the project out. I am able to reproduce the lava room dupe reliably. Simply dying in the lava causes the extra room nodes to appear. This is on a fresh copy of the master.

**Comment by KoBeWi** [comment] 2024-07-02 11:52
Ok so the room always duplicates, but I not always noticed it, because the duplicate was exactly at the position of the original. I'll look into it.

**Comment by KoBeWi** [comment] 2024-07-02 14:13
Fixed the sample project in 725b96ce1a9f2f6c66cd107d249d6884c1c48ff7
Looks like some physics bug, the player was repeatedly entering lava (despite being teleported away after first collision) and loaded the map again before it finished loading.

Check if it's fixed in your project too.

**Comment by HeiMao808** [comment] 2024-07-03 08:51
Getting this error now. It's still limited to the conditions I shared earlier.

![RoomTransition Error](https://github.com/KoBeWi/Metroidvania-System/assets/13976820/8739e0a2-369d-4da3-b3e6-01494106350a)

**Comment by KoBeWi** [comment] 2024-07-03 13:19
Looks like your new room did not load for some reason? Or it doesn't have RoomInstance. But it should break any transition, not only restart, so idk what is happening.

If you are able to share the project I can take a look.

**Comment by HeiMao808** [comment] 2024-07-04 08:11
I tried making a repo, it's been a while... Added you as a collaborator.

**Comment by KoBeWi** [comment] 2024-07-04 10:57
You could've just sent me ZIP in a DM or something.

I'm not sure if it's an issue I can fix in the plugin. It's problem with your `restart_game()`. You are loading a map and teleporting the player at the same time. Game frees the map, MetSys loads a map (it's independent from Game), but the previous instance is invalid (because you are in the middle of transition). I tried setting instance to null and it results in a glitch.

You can fix it on your side by awaiting `room_loaded`.
```GDScript
func reload_game():
	var save_manager := SaveManager.new()
	save_manager.load_from_text(SAVE_PATH)
	load_room(save_manager.get_value("current_room"))
	await room_loaded
	player.position = save_manager.get_value("save_position")
```

**Comment by HeiMao808** [comment] 2024-07-05 02:14
Thanks, it's working!

**Closed** 2024-07-05 10:21 UTC
