### ISSUE TITLE
empty start room

### ISSUE THREAD

**Issue by D0NM** [KoBeWi/Metroidvania-System#2] opened 2023-11-02 15:01 UTC
Om starting the sample game with Godot 4.2 beta 4
I get an epty start room with HUD (mini-map + 0/6 collectibles)
the hero is not seen.

**Comment by KoBeWi** [comment] 2023-11-02 20:15
Can't reproduce. I launched the project from freshly downloaded ZIP and it works correctly. Do you get any errors in the console? Maybe try deleting user data folder.

**Comment by D0NM** [comment] 2023-11-02 20:50
i used git clone.
now downloaded the whole project as .zip

it did show some problems on the screen (but the editor did restart so i could not read the errors)

then godot restarted and overwrote the log file.

-------------

The room is not empty now. It is as it should be.

**Comment by KoBeWi** [comment] 2023-11-02 20:55
Cloned and zip version are pretty much the same, so it's weird that it wouldn't work 🤔
The restart on first launch is expected, as the singleton needs to be initialized.

> but the editor did restart so i could not read the errors

If you run with the external console, they'd still be visible.

> The room is not empty now. It is as it should be.

Closing as resolved then.

**Closed by KoBeWi** 2023-11-02 20:55 UTC
